arch: arm64
os: linux
dist: xenial
language: ruby
services:
  - docker

before_install: 
  # check archicture. .com does not support arm atm.
  - dpkg --print-architecture
  
  # installing newer docker
  - sudo apt-get update
  
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  
  # installing the faas-cli
  - curl -sSL https://cli.openfaas.com | sudo sh

jobs:
  include:
<<<<<<< HEAD
    - stage: OpenFaas login
=======
    - stage: Create OpenFaas secrets 
>>>>>>> fd12efd4d05cbb5109ffe292eb57f3cc617d19b7
      script:
        - echo -n $OPENFAAS_PASS | faas-cli login --username admin --password-stdin -g https://gateway.christoffernissen.me
        - echo -n $INFLUX_USER | faas-cli secret create influx-user -g https://gateway.christoffernissen.me
        - echo -n $INFLUX_PASS | faas-cli secret create influx-pass -g https://gateway.christoffernissen.me

<<<<<<< HEAD
      - stage: functions
        script:
          - faas-cli up -f iot/iot-assignment2.yml --env write_debug=true
          # - faas-cli up -f iot/iot-ml-func.yml --env write_debug=true

      - stage: mqtt helper container
        script:
          - docker build -f iot/helper/Dockerfile iot/helper -t stifstof/iotmqttinterceptor
          - docker push stifstof/iotmqttinterceptor:latest
=======
    - stage: functions
      script:
        - echo -n $OPENFAAS_PASS | faas-cli login --username admin --password-stdin -g https://gateway.christoffernissen.me
        - faas-cli up -f iot/iot-assignment2.yml --env write_debug=true
        # - faas-cli up -f iot/iot-ml-func.yml --env write_debug=true

    - stage: mqtt helper container
      script:
        - docker build -f iot/helper/Dockerfile iot/helper -t stifstof/iotmqttinterceptor
        - docker push stifstof/iotmqttinterceptor:latest
>>>>>>> fd12efd4d05cbb5109ffe292eb57f3cc617d19b7

  # kubectl run --image=stifstof/iotmqttinterceptor iotmqttinterceptor-app --env="mqtt-pass="
  
