arch: arm64
services:
  - docker
script:
  - dpkg --print-architecture
  
  # installing newer docker
  - sudo apt-get update
  
  # installing the faas-cli
  - curl -sSL https://cli.openfaas.com | sudo sh
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - faas-cli build -f cstest.yml

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      - faas-cli push -f cstest.yml
      - faas-cli login --username admin --password="$OPENFAAS_PASS" -g http://christoffernissen.me:8080
      - faas-cli deploy -f cstest.yml
    fi

    