sudo: required

arch:
  - armhf

services:
  - docker

language: python3

cache: yarn

before_install:
  # installing newer docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # installing the faas-cli
  - curl -sSL https://cli.openfaas.com | sudo sh
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - faas-cli build -f cstest.yml
  - faas-cli push -f cstest.yml
  - faas-cli login --username admin --password="$OPENFAAS_PASS" -g http://christoffernissen.me:8080
  - faas-cli deploy -f cstest.yml


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then

    fi
  # you can deploy to a dev or prod (whatever) environment at this stage